### ISSUE TITLE
Accordion item header too big

### ISSUE THREAD

**Issue by TLuesebrinck** [django-cms/djangocms-frontend#119]
Adding "{{ instance.font_size }}"  to the button is not necessary, the button is already inside a h tag. Adding a fs-2 class make the header twice as big.

**Comment by fsbraun** [comment]
Hi @TLuesebrinck ! Can you elaborate? The header tag and font-size should align since otherweise the button tag overwrites the header font size. Which version of bootstrap5 are you using?

**Comment by TLuesebrinck** [comment]
Version 5.2.3
The sample code on the b5 docs do not use this fs-2 class for the button. Even older versions don't do this. 
https://getbootstrap.com/docs/5.2/components/accordion/

**Comment by fsbraun** [comment]
See #120. Now if the header size is unset (new default), the accordion item header is not changed in size.

**Comment by TLuesebrinck** [comment]
There is more wrong, I think. The h2 tag must have the class "accordion-header"

**Comment by fsbraun** [comment]
True. Instead, it reads `mb-0`. Both classes have the same effect, but semantically the needs to be `accordion-header`. Thanks for pointing this out!
