### ISSUE TITLE
Add djangocms-text-ckeditor support to images

### ISSUE THREAD

**Issue by raffael-mnhn** [django-cms/djangocms-frontend#127]
**Is your feature request related to a problem? Please describe.**
I want to embed images in ckeditor text plugins

**Describe the solution you'd like**
add text_enabled = True to the plugins where it makes sense

**Describe alternatives you've considered**
use djangocms-picture instead. This confuses editors.

**Additional context**

**Comment by fsbraun** [comment]
@raffael-mnhn Thanks for the suggestion! 

Can I add the idea to having a reduced form for text-embeded images for usability reasons? (Popup inside a popup is small.)

**Comment by raffael-mnhn** [comment]
Yeah, that probably makes sense. Although you can also maximize the CKEditor.

**Comment by i-salameh95** [comment]
what about webp images ? they are still not supported.
