### ISSUE TITLE
Float pictures

### ISSUE THREAD

**Issue by raffael-mnhn** [django-cms/djangocms-frontend#128]
**Is your feature request related to a problem? Please describe.**
I want to be able to have images float left or right.

**Describe the solution you'd like**
Add an option in the image ui that would allow to easily set the float-(sm,md,lg,xl)-begin and -end classes.

**Describe alternatives you've considered**
Content editor unfriendly alternatives are to add the classes manually.

**Additional context**

**Comment by baravkareknath** [comment]
Hi raffael-mnhn and fsbraun Is this task completed or not? if not can you assign to me

**Comment by raffael-mnhn** [comment]
I don't think it's completed

**Comment by baravkareknath** [comment]
Hi fsbraun and raffael-mnhn thanks to assign this task to me and thanks for the replay.

**Comment by baravkareknath** [comment]
Hi fsbraun and raffael, same issue gets in https://github.com/django-cms/djangocms-picture.git so can I resolve this issue in djangocms-picture.git repository?

**Comment by fsbraun** [comment]
@baravkareknath You can do both. Chose one place to start and after finishing start the second. There's already alignment options which according to https://getbootstrap.com/docs/5.3/content/images/#aligning-images should be turned into float classes.

**Comment by baravkareknath** [comment]
Hi fsbraun I am creating patch for  repository - https://github.com/django-cms/djangocms-picture.git  
so can I submit it for review purpose.
