### ISSUE TITLE
Missing `django.mo` file for french translations

### ISSUE THREAD

**Issue by adrien-delhorme** [django-cms/djangocms-frontend#139]
**Describe the bug**
Other languages have their `django.mo` file committed in the repository (and in the distributed package), but not french.

**Expected behavior**
I first thought that the policy of this package was to not commit the `*.mo` files, but other `django.mo` are committed: so I think the django.mo file for french language is just missing.

**Comment by raffaellasuardini** [comment]
The resolution for this issue can be attributed to [Fabian's pull request](https://github.com/django-cms/djangocms-frontend/pull/162).

**Comment by fsbraun** [comment]
@raffaellasuardini Thanks, I was not aware! 😎
