### ISSUE TITLE
Wrong po file for spanish translation 

### ISSUE THREAD

**Issue by bielfrontera** [django-cms/djangocms-frontend#147]
**Describe the bug**
The new file `djangocms_frontend/locale/es/LC_MESSAGES/django.po` does not contain the spanish translation but the german.

Not sure if there is a team for the spanish translation at transifex or I could submit a PR with the translation.

**Comment by fsbraun** [comment]
Spanish translations would be sensational!

**Comment by fsbraun** [comment]
@bielfrontera I just checked transifex: Spanish translations are empty. If you let me know your email, I can invite you to the team. Please let me know privately on slack: https://django-cmsworkspace.slack.com/archives/CQ97U91UM
