### ISSUE TITLE
Navbar does not collapse on mobile devices

### ISSUE THREAD

**Issue by hgkornmann** [django-cms/djangocms-frontend#189]
**Describe the bug**
I added a navbar like this:
![image (1)](https://github.com/django-cms/djangocms-frontend/assets/161461370/6e7af1da-d996-4e7e-bfa4-da78ef14c15f)
![image](https://github.com/django-cms/djangocms-frontend/assets/161461370/dd613f93-a117-490b-8128-447109d537c5)

But the navbar does not collapse on mobile devices.

**To Reproduce**
You can rebuild the structure and test it.

**Expected behavior**
The navbar should be collapse on mobile devices.

**Screenshots**
See screenshots

**Desktop (please complete the following information):**
 - Browser: Opera One(Version: 107.0.5045.21)
 - Version: DjangoCMS V4.1

**Additional context**

**Comment by fsbraun** [comment]
Fixed with #192
