### ISSUE TITLE
Icons not appear with navigation links

### ISSUE THREAD

**Issue by hgkornmann** [django-cms/djangocms-frontend#190]
**Describe the bug**
I added two icons for email and phone with an navigation link.
The icons are not shown.

![image (3)](https://github.com/django-cms/djangocms-frontend/assets/161461370/91ced075-1469-4796-96ff-69b6b6f32efe)
![image (2)](https://github.com/django-cms/djangocms-frontend/assets/161461370/ec83590b-09c1-41aa-ac4d-651e6ab46b85)
![image (1)](https://github.com/django-cms/djangocms-frontend/assets/161461370/64aee294-1ec8-46fc-9eb6-e4daa6d4491a)
![image](https://github.com/django-cms/djangocms-frontend/assets/161461370/fbe9035a-6fcb-4e2e-a5bb-17411dd94665)

**To Reproduce**
Add a navigation link and set a icon.

**Expected behavior**
Icons should be shown beside .

**Screenshots**

**Desktop (please complete the following information):**
 - Browser Opera One(Version: 107.0.5045.21)
 - Version DjangoCMS 4.1

**Additional context**

**Comment by fsbraun** [comment]
Fixed in #192
