### ISSUE TITLE
[BUG] Wrong site used in link plugin

### ISSUE THREAD

**Issue by adrien-delhorme** [django-cms/djangocms-frontend#196]
**Describe the bug**

When using a LinkPlugin inside a static placeholder, the wrong (django) site is used when generating the link to a page located on another (django) site.

**To Reproduce**
Consider a multi-site setup of django-cms: Site A and Site B.

### On Site A
There is a page "Page A" `site-a.com/path/to/page-a/`.

### On Site B
We create a LinkPlugin inside a static placeholder (or in a model's PlaceholderField like a djangocms-blog Post).
We choose "Site A > Page A" in the internal page field.
The generated link points to `site-b.com/path/to/page-a/` (it does not exist).

**Expected behavior**
The generated link must point to `site-a.com/path/to/page-a/`

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Firefox
 - Version: 123.0.1

**Additional context**
The link is correct when I remove `and cms_page is not None` in this condition:
https://github.com/django-cms/djangocms-frontend/blob/7d2d682fa8898de8502a64f5040811597311c6de/djangocms_frontend/contrib/link/models.py#L70

**Comment by fsbraun** [comment]
Going through the logic, your suggestion seems right. Thanks for pointing this out!

**Comment by fsbraun** [comment]
Fixed in #195
