### ISSUE TITLE
Icons are not correctly placed when navbar is collapsed

### ISSUE THREAD

**Issue by hgkornmann** [django-cms/djangocms-frontend#200]
The icons beside a link, inside a navbar are not at the correct place:
When the navbar is collapsed the icons are not left and right.
Instead there are at the top and bottom.

See attached pictures

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Opera]
 - Version [3.11.5]

![image (2)](https://github.com/django-cms/djangocms-frontend/assets/161461370/7f9d371c-e057-4390-8916-e8b73dc62d2b)
![image (1)](https://github.com/django-cms/djangocms-frontend/assets/161461370/cf9ed6ac-bbf9-456d-9556-82db7f7b7993)
![image](https://github.com/django-cms/djangocms-frontend/assets/161461370/4fb1a1d5-4cf4-4e7f-8bc0-cc3736c92b7e)
![image (3)](https://github.com/django-cms/djangocms-frontend/assets/161461370/dce37651-1917-431b-a47d-112a05749c36)

**Comment by baravkareknath** [comment]
Hi Team,
Can I look in it?
Can you assign me this issue.

**Comment by hgkornmann** [comment]
@fsbraun : Could you please give me help which file has to be modified for solving this issue

**Comment by fsbraun** [comment]
@hgkornmann Would be great if you gave it a go! I'd start looking here: https://github.com/django-cms/djangocms-frontend/blob/master/djangocms_frontend/contrib/navigation/templates/djangocms_frontend/bootstrap5/navigation/default/link.html
(Added you as assignee, too 😃)

**Comment by fsbraun** [comment]
Released with version 1.3.3
