### ISSUE TITLE
Link / Button plugin - internal link gets preselected from 1.3.0

### ISSUE THREAD

**Issue by aacimov** [django-cms/djangocms-frontend#206]
**Describe the bug**
It happens on versions 1.3.0 and above, 1.2.2 works fine. When adding Link/Button plugin inside TextPlugin - Internal link preselects the first page from the page tree.

**To Reproduce**
1. Add some text in a TextPlugin
2. Select it and add Link/Button plugin from CMSPlugins
3. Internal link preselects first page from the tree

**Expected behavior**
Internal link should not preselect anything since if you wish to add an e-mail link (through Link settings) it returns the error that 2 types cannot be selected.

**Screenshots**
<img width="678" alt="Screenshot 2024-04-19 at 09 29 12" src="https://github.com/django-cms/djangocms-frontend/assets/912266/d2c1c7f0-2125-4b52-abb7-ad8aa95aa71a">

**Desktop:**
 - OS: MacOS Monterey
 - Browser Chrome
 - Plugin version 1.3.0/1.3.1
 - Django CMS 4.1.0
 - Django 4.2.11

**Comment by sebbschbo** [comment]
Thx @fsbraun for your work!
