### ISSUE TITLE
Change column page broken.

### ISSUE THREAD

**Issue by TLuesebrinck** [django-cms/djangocms-frontend#207]
![edit cloumn broken](https://github.com/django-cms/djangocms-frontend/assets/93937334/6a262f52-436a-4bb2-a77b-aa6156207cfd)
The main ccs class/property which causes this, comes from the form.css (see img) which is part of the django standard admin interface.  I tested django 4/5 and also tried to go a version backwards for djangocms-frontend and admin-style but the problem remains. The spacing section also show a flaw, and there may be more I am not aware of.

**Comment by fsbraun** [comment]
Closed with #208
