### ISSUE TITLE
Link/Button admin page failed to show the list of page to select an internal link 

### ISSUE THREAD

**Issue by TLuesebrinck** [django-cms/djangocms-frontend#209]
The admin page for the link button plugin don't show the list of pages. The dropdown shows only "The result could not be loaded". Clicking the drop down cuase a console error :  

jquery.min.2c872dbe60f4.js:2 
         GET https://mydomain/@dcf-links/link:autocomplete?app_label=app&model_name=model&field_name=field 404 (Not Found) 

I am not absolute certain but I think this occured after installing the latest djangocms-fontend version.

**Comment by fsbraun** [comment]
Sorry, I cannot reproduce the issue. The URL looks ok. Link app's `ready()` method registers the URL with Django. Can you check if it is registered? (It should be, since otherwise `reverse` would fail.)

**Comment by fsbraun** [comment]
PS: I plan to move the URL into the admin space soon.

**Comment by TLuesebrinck** [comment]
How do I do that?

One time I got this error.

[image: image.png]

Am Mi., 24. Apr. 2024 um 13:23 Uhr schrieb Fabian Braun <
***@***.***>:

**Comment by fsbraun** [comment]
For example, by using django-extensions and `./manage.py  show_urls`.

**Comment by TLuesebrinck** [comment]
The command line output this warning message:
I have not seen this before, could this be part of the problem?

 python manage.py show_urls
/usr/share/django-cms/env/lib/python3.11/site-packages/django/db/backends/utils.py:98:
RuntimeWarning: Accessing the database during app initialization is
discouraged. To fix this warning, avoid executing queries in
AppConfig.ready() or when your app modules are imported.
  warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)

I can find the link in the command output:
***@***.***/link:autocomplete
djangocms_frontend.contrib.link.views.AutocompleteJsonView
 dcf_autocomplete:ac_view

But when I test the link in the browser, it is unknown

^(?P<page>.+\.html)
^(?P<page>.+\.mp4)$
sitemap.xml
sitemap.xml
taggit_autosuggest/
robots.txt
en/
^media/(?P<path>.*)$
^static/(?P<path>.*)$
The current path, @dcf-links/link:autocomplete, didn’t match any of these.


Am Mi., 24. Apr. 2024 um 14:40 Uhr schrieb Fabian Braun <
***@***.***>:

**Comment by fsbraun** [comment]
I have not looked at the issue for now, but instead

**Comment by TLuesebrinck** [comment]
Yes, with version 1.3.2, the internal link dropdown it is working again.
