### ISSUE TITLE
Outdated tag for footer

### ISSUE THREAD

**Issue by rcooke** [django-cms/djangocms-frontend#224]
**Describe the bug**
In file `djangocms_frontend/templates/djangocms_frontend.html`, line 31 says:
{% static_placeholder "Footer" %}

The "static_placeholder" tag does not seem to exist anymore.  I had to change it to:
{% static_alias "footer" %}

And also install/include "djangocms_alias_tags"

**To Reproduce**
1. Install sample setup with **djangocms myproject**
2. This installs the _frontend_ and sets up a new system with the templates.
3. But you wont get a footer!

**Comment by fsbraun** [comment]
@rcooke Thanks for pointing this out! It is, indeed, outdated. I tend towards removing the `<footer>` completely to keep a uniform codebase for django CMS 3 and 4 for the time being.

To actually get a footer, you need to use djangocms-alias with django CMS 4 as you indicate!
