### ISSUE TITLE
Is the lack of code highlighting a bug?[BUG]

### ISSUE THREAD

**Issue by baloyou** [django-cms/djangocms-frontend#226]
When I use the code plugin to add a piece of code, the content page does not display code highlighting.

The version of django-cms is 4.1.1, and I am using a virtual environment with venv. The issue exists by default after installation via pip.

![image](https://github.com/django-cms/django-cms/assets/5190664/11fb5b17-0b42-4a7a-82e5-2f5b3bf4d031)

![image](https://github.com/django-cms/django-cms/assets/5190664/43a84f0d-56c8-459c-be29-1c54b721d75d)

**Comment by fsbraun** [comment]
No, HTML's `<pre>` tag does not do code highlighting. There are JS libraries out there, which do this, such as [highlight.js](https://highlightjs.org). You would need to use one of those.

Out of the box, djangocms-frontend does only support features that are HTML native or provided by the frontend framework (which by default is Bootstrap 5).

**Comment by fsbraun** [comment]
There is a bug, however, since for code blocks the markup should read `<pre><code>the code goes here</code></pre>`. The inner `<code>` seems to be missing.

**Comment by fsbraun** [comment]
I just released djangocms-frontend 1.3.3 which should fix the `<pre><code>` part of the issue. And yes, you're not doing it right here 😉.

django CMS uses django-sekizai to avoid repeated inclusion of css or js. Do this instead:
```
{% load i18n cms_tags sekizai_tags %}

<{{ instance.code_type|default:"code" }}{{ instance.get_attributes }}>
<code>
{{ instance.code_content }}
</code>
</{{ instance.code_type|default:"code" }}>

{% addtoblock css %}<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.min.css">{% endaddtoblock %}

{% addtoblock js %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-python.min.js"></script>
{% addtoblock %}
```

See [here](https://docs.django-cms.org/en/latest/how_to/09-custom_plugins.html#handling-media) for more info in this.

**Comment by baloyou** [comment]
> I just released djangocms-frontend 1.3.3 which should fix the `\<pre\><code>` part of the issue. And yes, you're not doing it right here 😉.
> 
> django CMS uses django-sekizai to avoid repeated inclusion of css or js. Do this instead:
> 
> ```
> {% load i18n cms_tags sekizai_tags %}
> 
> <{{ instance.code_type|default:"code" }}{{ instance.get_attributes }}>
> <code>
> {{ instance.code_content }}
> </code>
> </{{ instance.code_type|default:"code" }}>
> 
> {% addtoblock css %}<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism.min.css">{% endaddtoblock %}
> 
> {% addtoblock js %}
>     <script src="//cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
>     <script src="//cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-python.min.js"></script>
> {% addtoblock %}
> ```
> 
> See [here](https://docs.django-cms.org/en/latest/how_to/09-custom_plugins.html#handling-media) for more.

This is so cool and very effective (I should have looked at the docs more, thanks again)

**Comment by fsbraun** [comment]
@baloyou I see you are using Chinese locales. If you wanted to have a more consistent user experience with Chinese labels etc., **and** would like to spend some time on it, **I would appreciate it if I could add you as a translator** to django CMS frontend! Every single string translated helps. Join us on discord and let me know! https://discord-main-channel.django-cms.org/

**Comment by baloyou** [comment]
My English is a bit poor (relying on translation software) and I am new to DjangoCMS, so when I am familiar with it, I am willing to participate in the work of Chinese. @fsbraun  :) :)

**Comment by fsbraun** [comment]
Thank you so much, @baloyou ! You'll find it's a great community! 

Translation software helps a lot and a good way to contribute! If you use it, you'll have the better understanding than I what the best Chinese translation for "Code", "Background", "Spacing", or "Visibility" is (taken from the dialogue window above). 

(I'd come up with "代码", "背景", "间距", and "能见度". Is that meaningful?)

**Comment by baloyou** [comment]
You're right, translation work gives me a better understanding of the framework (but I'll have to wait until I get familiar with the basic features) If you're asking me if the translation of "Code", "Background", "Spacing", or "Visibility" is appropriate, I think: exactly @fsbraun

**Comment by fsbraun** [comment]
🙌
Sure, no pressure. I just wanted to say, why I can see you adding value. Now, those officially are the first 4 words of the djangocms-frontend package translated to Chinese!! 🎉

**Comment by baloyou** [comment]
I've copied the corresponding .po file and I'll come back and share it with you if there's work.

I have another small question, though. I use "heading" to generate multiple layers of titles, and when I want to generate the corresponding "table of contents", the toc must be below the heading to display (the above is not good) Is this a bug?

![image](https://github.com/django-cms/djangocms-frontend/assets/5190664/f0723d69-a900-4d0e-a23e-66db378c91fe)

**Comment by fsbraun** [comment]
That's correct. If you want to display the toc at the top, put content and toc in a row with two columns, both with width 12 (i.e. full width). Put the content into the first column, the toc into the second, and in the columns dialogue change the display order: first the toc, then the content.

**Comment by fsbraun** [comment]
Background info: The toc information is collected as the page is rendered. This is a 1 pass process (due to speed) and hence the heading information for the toc is only available after all heading plugins have been rendered.

**Comment by baloyou** [comment]
hi @fsbraun ,I have a question about "link/button", assuming I have a large amount of data (e.g. 2000 pages) will the "internal link" drop-down box be displayed all at once? Will there be performance issues?

**Comment by fsbraun** [comment]
The link plugin and all plugins that use links use Django's Select2 Box to dynamically load pages. To further optimize, you can configure if the user needs to input a certain number of characters before the search starts: `DJANGOCMS_FRONTEND_MINIMUM_INPUT_LENGTH = 2` for example, if you want to start loading data only if the user has already entered two characters. Default is 0.

**Comment by baloyou** [comment]
Hi @fsbraun , I'm back again...   I saw instructions in this doc https://djangocms-frontend.readthedocs.io/en/latest/how-to/internal-link-targets.html but when I added DJANGOCMS_FRONTEND_MINIMUM_INPUT_LENGTH=2 to the settings.py, I opened it again link/button option, a syntax error occurred, is this related to version compatibility issues? (I'm djangocms 4.1.1 and frontend's version is 1.3.2)

![image](https://github.com/user-attachments/assets/d391f501-2a23-4ebb-b563-caedb31c1beb)

**Comment by fsbraun** [comment]
Well done! You found a regression! Will fix that in the next few hours! Thanks!

**Comment by baloyou** [comment]
hi @fsbraun , I'm back again again... 

I'd like to add a right-hand menu to the navigation, I defined a class like this:
```
class UserMenu(Menu):
    def get_nodes(self, request):
            return [
                NavigationNode("profile", reverse('account_profile'), 101, attr={'visible_for_anonymous': False}),
                NavigationNode("logout", reverse('account_logout'), 102, attr={'visible_for_anonymous': False}),
                NavigationNode("sign in", reverse('account_login'), 103, attr={'visible_for_authenticated': False}),
                NavigationNode("sign up", reverse('account_signup'), 104, attr={'visible_for_authenticated': False}),
            ]
menu_pool.register_menu(UserMenu)
```
Can I use {%show_menu%} or any other tag to display my menu above?

**Comment by fsbraun** [comment]
Yes, you can. But that will just add the entries to the menu (and not create a separate right-hand menu).

Alternatively, you can hardcode this into your `base.html` template. If you are using djangocms-frontend's default tempalte, then this contains something like:
```
{% block navbar %}
    <nav class="navbar {% block navbar_options %}navbar-expand-lg navbar-dark bg-dark{% endblock %}">
        <div class="container">
            <a class="navbar-brand" href="/">{% block brand %}{% endblock %}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">{% block menubar %}{% show_menu 0 100 100 100 'bootstrap5/menu.html' %}{% endblock %}</ul>
                {% block searchbar %}{% endblock %}
            </div>
        </div>
    </nav>
{% endblock %}
```

You'd just have to add a bloc `searchbar` with your right-hand menu:

```
{% block searchbar %}
    {% here goes your (hard-coded) markup for the right-hand menu %}
{% endblock %}
```

**Comment by baloyou** [comment]
hey @fsbraun I'm back again again again!
```
● a
  ○ a-1
  ○ a-2
    ■ a-2-1
    ■ a-2-2
  ○ a-3
    ■ a-3-1
    ■ a-3-2
● b
  ○ b-1
  ○ b-2
● c
  ○ c-1
  ○ c-2
```

I've created multiple levels of pages and want to create submenus for each root page (displayed on the left side of the page) and when I click on any subpage, the same root menu is displayed.

I found a template tag, `{% show_menu_below_id "iot-hobby" 0 %}` but it has to manually specify the page id (if I have multiple root pages, I need to create the template file repeatedly)

Is there a better way to do it:)

That's what I want to achieve:

![image](https://github.com/user-attachments/assets/d55b11d3-4281-4473-8a7a-60ad2c7f99f5)

**Comment by baloyou** [comment]
hi @fsbraun I'm back again again again!!!

When I create a new page, I occasionally get a situation where the slug field is not editable (there is an extra readonly attribute) and I log in with a superuser. This happened once in the morning, it was automatically restored later, and now the problem is recurring (I'm sure I didn't make any changes, and I've tried logging back in and clearing my cache)

```
<input type="text" name="slug" maxlength="255" readonly="" language="zh-hans" data-decoder="zh" required="" aria-describedby="id_slug_helptext" id="id_slug">
```
![image](https://github.com/user-attachments/assets/fa3c9fe9-efbc-4765-b976-7757fe94d4a2)

**Comment by baloyou** [comment]
@fsbraun ..
I'm looking for the source of the problem, but after 20 minutes the readonly attribute is gone again, but I'm sure there's something wrong.
```
<input type="text" name="slug" maxlength="255" language="zh-hans" data-decoder="zh" required="" aria-describedby="id_slug_helptext" id="id_slug" data-enpassusermodified="yes">
```

**Comment by fsbraun** [comment]
It's a known and fixed issue. The fix is scheduled for the next release. https://github.com/django-cms/django-cms/issues/7866

**Comment by baloyou** [comment]
> It's a known and fixed issue. The fix is scheduled for the next release. [django-cms/django-cms#7866](https://github.com/django-cms/django-cms/issues/7866)
> 
> Thank you for your rigorous reporting! This really helps. I appreciate it!

You are awesome!!! is there any way I can avoid this problem before updating the version?

**Comment by fsbraun** [comment]
At your own risk you can install from the release branch: `pip install ***@***.***/4.1.x`. Am 17.07.2024 um 09:55 schrieb baloyou ***@***.***>:﻿

It's a known and fixed issue. The fix is scheduled for the next release. django-cms/django-cms#7866
Thank you for your rigorous reporting! This really helps. I appreciate it!

You are awesome!!! is there any way I can avoid this problem before updating the version?

**Comment by baloyou** [comment]
> 您可以自行承担风险从发布分支进行安装：`pip install git+ https://github.com/django-cms/django-cms@release/4.1.x`。

Well, thank you, I don't want to update just yet. This problem occasionally arises, and if you can know the cause, you can avoid it.

**Comment by baloyou** [comment]
hi @fsbraun I'm back again x 4

I have a question about "page permissions".

I want certain pages to be accessible only to a specified group of users.
1. I added a user group
2. In the "Advanced Settings" of the page, add a user group in the "View restrictions".
3. Add the user to the specified user group
At this point, the page is accessible.
4. I remove the user from the user group
At this point, the page is still accessible???!!!
5. Re-enter the "Advanced Settings" on the page, modify any of the options, and save
At this time, the user cannot access the page.

After repeated tests, it seems that after users join and leave the group, they must save it again in the "Advanced Settings" of the page for the permissions to take effect.

However, it doesn't matter what options are saved (it seems that the cache is flushed?). ）

**Comment by fsbraun** [comment]
Hey Baloyou!

That sounds like a caching issue, indeed. Can you raise a separate issue on https://github.com/django-cms/django-cms/issues?

My hypothesis:

The cache is flushed once you safe the advanced settings. But it is not flushed if you change group membership.

Thanks, Fabian

**Comment by baloyou** [comment]
hi @fsbraun i added issue: https://github.com/django-cms/django-cms/issues/7962

I think you're right.
