### ISSUE TITLE
Show content element depending on user auth status

### ISSUE THREAD

**Issue by mavoIn** [django-cms/djangocms-frontend#232]
Is there an easy way to show content elements depending if a user is logged in or logged out? 

Currently, I am only aware of the "Authorization" function at page level. I would find it helpful if there is a content element that I could insert in the same way as "Spacing" and decide here whether the child elements are visible or not depending on the login status.

**Comment by fsbraun** [comment]
To create a custom plugin that shows its children only if the user is logged in, you can follow the steps below:

1. Start by creating a new Django application for your plugin. You can use the command `python -m manage startapp` to set up the basic layout for your plugin app. Remember to add your plugin to `INSTALLED_APPS`.

2. Create a file called `cms_plugins.py` in your new application. This is where you will define your plugin class.

3. In `cms_plugins.py`, you will need to import the necessary modules and define your plugin class. Here's an example of how you can do this:

```python
from cms.plugin_base import CMSPluginBase
from cms.plugin_pool import plugin_pool
from cms.models.pluginmodel import CMSPlugin
from django.utils.translation import gettext_lazy as _

@plugin_pool.register_plugin
class LoggedinPlugin(CMSPluginBase):
    model = CMSPlugin
    render_template = "loggedin_plugin.html"
    cache = False
```

4. In the `render` method of your plugin class, you can add logic to check if the user is authenticated. If they are, you can render the child plugins; if they're not, you can return an empty context. Here's an example:

```python
def render(self, context, instance, placeholder):
    if context['request'].user.is_authenticated:
        return super().render(context, instance, placeholder)
    else:
        return {}
```

5. Finally, you will need to create a template for your plugin. This template will be used to render the plugin on your website. In this template, you can use the `{% render_plugin %}` template tag to render the child plugins of your custom plugin. Here's an example:

```html
{% for plugin in instance.child_plugin_instances %}
    {% render_plugin plugin %}
{% endfor %}
```

Please note that this is a simplified example and you might need to adjust it according to your specific needs.

Sources:
- [How to create Plugins](https://docs.django-cms.org/en/latest/how_to/09-custom_plugins.html)
- [Github Issue Comment](https://github.com/django-cms/django-cms/issues/5085)

**Comment by fsbraun** [comment]
Also check out django CMS support: https://www.django-cms.org/en/support/

**Comment by mavoIn** [comment]
Perfect! Works as excepted!
