### ISSUE TITLE
Problem with bootstrap carousel after migrate from B4

### ISSUE THREAD

**Issue by TLuesebrinck** [django-cms/djangocms-frontend#27]
I use the bootstrap carousel plugin on my page and its seams it is not correct migrated to the frontend.
The page lording stops with an exception because the "Bootstrap4CarouselPlugin" could not be found.

**Comment by fsbraun** [comment]
@TLuesebrinck Thanks for reporting this issue. Apparently, the `migrate` command does not migrate carousels. I would like to come up with a fix. Would you have the opportunity to test it?

**Comment by TLuesebrinck** [comment]
yes if it is fixed I can test it.

Am Mo., 9. Mai 2022 um 13:33 Uhr schrieb Fabian Braun <
***@***.***>:

**Comment by fsbraun** [comment]
Can you please install the latest master branch on your develop system using `pip install git+https://github.com/django-cms/djangocms-frontend@master#egg=djangocms-frontend` and let the migration run one more time? 

Would you also share if it did work? Thank you!

**Comment by TLuesebrinck** [comment]
the problem still exist

  File ".....\env\lib\site-packages\cms\plugin_pool.py", line 186, in
get_plugin
    return self.plugins[name]
KeyError: 'Bootstrap4CarouselPlugin'

Am Mo., 9. Mai 2022 um 14:45 Uhr schrieb Fabian Braun <
***@***.***>:

**Comment by fsbraun** [comment]
@TLuesebrinck Did you run `./manage.py frontend migrate` a second time? It should have displayed how many plugins were converted (an integer like `2` depending how many carousel plugins you have.):

        Migrating plugins
              2
        Successfully migrated plugins
        
        Checking installed apps for potential link destinations
        No further link destinations found. Setup complete.

as opposed to

        Migrating plugins
        
        Successfully migrated plugins
        
        Checking installed apps for potential link destinations
        No further link destinations found. Setup complete.

Also note that carousel plugins will only be migrated if `djangocms_bootstrap4.contrib.bootstrap4_carousel` is in `INSTALLED_APPS`.  The migration process will then change the type to `CarouselPlugin` to avoid the above error message.

**Comment by fsbraun** [comment]
This actually is an indication that 

(a) the latest master is not installed (using the pip command I mentioned). It includes the carousel migration that was missing (https://github.com/django-cms/djangocms-frontend/blob/41cf447f44b15930fb5b873f9c2a70fde08f8902/djangocms_frontend/management/bootstrap4_migration.py#L257). Can you double check that this line is present in your setup?  **or**

(b) you already deleted or emptied the `djangocms_bootstrap4_boostrap4_carousel` table from the DB (but this should not be the case when you work in the backup)

**To get rid of the module not found error please change** `djangocms_frontend.contrib.forms` **to** `djangocms_frontend.contrib.frontend_forms`.

**Comment by fsbraun** [comment]
@TLuesebrinck The fix has been merged to the master branch of the repo. If you reinstall `pip install git+https://github.com/django-cms/djangocms-frontend@master#egg=djangocms-frontend` you should be able to migrate the carousels with link information. Feel free to close this issue if it works!

**Comment by TLuesebrinck** [comment]
It works, the links are there. The pip install command does not overwrite
the current install of the djangocms-frontend. I have to uninstall it first
to get the latest version, maybe this is expected, I thought the link
install the latest from the git repository.

Am Di., 10. Mai 2022 um 10:49 Uhr schrieb Fabian Braun <
***@***.***>:
