### ISSUE TITLE
failed saving picture plugin in text editor

### ISSUE THREAD

**Issue by TLuesebrinck** [django-cms/djangocms-frontend#33]
My page is migrated to frontend from Bootstrap 4

- Edit text plugin with picture plugin
- select the picture plugin
- click save

The dialog tell me I have to correct an error listed below. But there is no field marked or anything else. 
In the browser console log list some errors related to django select 2

Uncaught TypeError: Cannot read properties of undefined (reading 'define')

![image](https://user-images.githubusercontent.com/93937334/168258141-cc86851f-e1cd-4c4a-8da9-94f76db3ed11.png)

**Comment by fsbraun** [comment]
Does this concern djangocms-frontend's Image Plugin or djangocms_picture plugin? Do you know from what url this `de.js` file is loaded?

**Comment by fsbraun** [comment]
Did you have a non-standard template for the picture plugin (which should now be an Image Plugin)?

**Comment by fsbraun** [comment]
Thinking about this, I'd suggest two features for the migration command and a bugfix:

Feature:
(a) Check the settings.py file for settings that need to be adjusted
(b) Check if migrated plugins are compatible with the settings and issue a warning if not

Bugfix:
(c) Show template choice field if template has invalid value (currently it's hidden if it has only one choice)

**Comment by TLuesebrinck** [comment]
The problem is caused by a DJANGOCMS_PICTURE_TEMPLATES setting, the template folder with the html file exist.
