### ISSUE TITLE
Link model settings for blog pages, cause: Name error, name '_' is not defined

### ISSUE THREAD

**Issue by TLuesebrinck** [django-cms/djangocms-frontend#34]
Removing the "_" fix this.

You have djangocms_blog installed. Consider adding the following
lines to your settings.py:

    DJANGOCMS_FRONTEND_LINK_MODELS = [
        {
            "type": _("Blog pages"),
            "class_path": "djangocms_blog.models.Post",
            "filter": {"publish": True, "app_config_id": 1},
            "search": "translations__title",
        },
    ]

**Comment by fsbraun** [comment]
True! 

Better to add

from django.utils.translation import gettext_lazy as _
