### ISSUE TITLE
Code plugin admin hardcodes URL to "ace" JS module

### ISSUE THREAD

**Issue by greyhare** [django-cms/djangocms-frontend#48]
**Describe the bug**
The Frontend "Code" plugin's admin templates have hardcoded URLs (including version numbers) for loading the JS for the "ace" module, which is used as a code editor. This breaks badly on systems without internet access.

**To Reproduce**
1. Be offline, and have a properly setup development project, fully migrated.
2. Run `manage.py runserver` as normal. Login as an admin, and edit a page. Add a Frontend Code plugin.
3. In the admin pane that opens to edit the new plugin, there is just empty space next to "Code:". The plugin cannot be saved due to the missing field.
4. Check Safari's debug console and see `Failed to load resource: A server with the specified hostname could not be found. https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.14/ace.js`

**Expected behavior**
Some kind of functioning code editor should appear. Or it should fallback to a `textarea`.

**Screenshots**
Not readily available due to network isolation, sorry.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 15.6 (16613.3.9.1.7, 16613)

**Additional context**
The offending URL is in `contrib/content/templates/djangocms_frontend/admin/code.html` line 6:

```html
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.14/ace.js" integrity="sha512-6ts6Fu561/yzWvD6uwQp3XVYwiWNpWnZ0hdeQrETqtnQiGjTfOS06W76aUDnq51hl1SxXtJaqy7IsZ3oP/uZEg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```

In `django_bootstrap4`, to solve a similar situation, I simply have to set the `BOOTSTRAP4` setting, using code that looks something like:

```python
BOOTSTRAP4 = {
    'css_url': f'{node_root}bootstrap/dist/css/bootstrap.css',
    'javascript_url': f'{node_root}bootstrap/dist/js/bootstrap.js',
    'jquery_url': f'{node_root}jquery/dist/jquery.js',
    'include_jquery': 'full'
}
```

I use `npm` to get Bootstrap (and jQuery and Popperjs) from our internal mirror. (Bootstrap5 doesn't use jQuery, but I do.)

**Comment by marksweb** [comment]
@greyhare Thanks for raising. We'll have a look at this.

**Comment by marksweb** [comment]
@fsbraun Implementing a similar setting to the BS4 app might make most sense here. What do you think?

**Comment by fsbraun** [comment]
@greyhare Thanks very much for reporting this. The ace editor is used in the plugin admin (and hence is part of the admin site) and is not loaded elsewhere. I'd suggest the follow the Django convention (which - except here - is also followed by django CMS) to include the ace editor as a static file, just as Django admin's jQuery or `CMS.jquery`. This ensures that it does not interfere with the site setup **and** can be used when not connected to the internet.

@marksweb I fear we have exactly this issue with `djangocms-bootstrap4´ and `djangocms-snippet`. I'll create 3 separate PR.

**Comment by greyhare** [comment]
Sounds fine to me. I had no idea how big ace is or how feasible it was to pull in statically. I figured it was pulled in via CDN for a reason. (I use MathJax with my Sphinx docs at work, and statically pulling it in would be some 100 MB of data. So it's not my first choice.)

**Comment by greyhare** [comment]
And yes, you have exactly this issue with `djangocms-bootstrap4`. I found it there first and found this project while trying to figure out what to migrate to since it seemed dead. `djangocms-bootstrap5` has the same problem as well, I believe.

**Comment by fsbraun** [comment]
@greyhare #49 fixes this issue. Would you like to test it? Try:

    pip install git+https://github.com/django-cms/djangocms-frontend.git@develop#egg=djangocms-frontend[static-ace]

(Remember to escape the square brackets to avoid your shell to match files) 

Then add `djangocms_static_ace` to your project's `INSTALLED_APPS`.

**Comment by greyhare** [comment]
The system in question doesn't have Internet access (which is what caused the problem in the first place), so pip install from Github will fail.

Do you have a command that'll let me download a tarball, which I can manually copy over and then install?

**Comment by fsbraun** [comment]
Well, I guess pip is the standard way of managing python packages. Of course you can download tar balls from GitHub and install them.

https://github.com/django-cms/djangocms-frontend/archive/refs/heads/master.zip

You'll also need djangocms-static-ace:
https://github.com/django-cms/djangocms-static-ace/archive/refs/heads/main.zip

**Comment by greyhare** [comment]
Pip itself is fine. We have an internal mirror of PyPI that we use, and I install djangocms-frontend via that. It's the git+https://github.com/... part that fails, because github.com doesn't resolve.

**Comment by greyhare** [comment]
OK, managed to get `djangocms-static-ace` 1.1.0 manually installed from our PyPI mirror, but `djangocms-frontend[static-ace]` got me:
```
WARNING: djangocms-frontend 0.9.4 does not provide the extra 'static-ace'
```
Downloading and installing the zip with pip worked:
```
pip install ~/master.zip[static-ace]
```
And I now have the code editor!

Looking forward to this being in a release.

Thanks!
