### ISSUE TITLE
Top-level Accordion <div> is missing the `accordion` class

### ISSUE THREAD

**Issue by greyhare** [django-cms/djangocms-frontend#51]
**Describe the bug**
The accordion plugin looked wonky, so I looked at the DOM and compared it to the Bootstrap docs, and didn't see the `accordion` class applied to the top-level `<div>`. Adding it manually in the browser debug pane made it look right.

**To Reproduce**
1. Add an Accordion element to a page.
2. Add some boilerplate to the tags.
3. See below.

**Expected behavior**

**Screenshots**
What it looks like:
![acc-wo-styling](https://user-images.githubusercontent.com/18636280/187796011-ccd00f3e-c00f-4a3a-8889-16ba782edbec.png)
![code-wo-accordion-class](https://user-images.githubusercontent.com/18636280/187796008-b1688620-4296-4ab4-b426-9768533c8588.png)

What it should look like:
![acc-with-styling](https://user-images.githubusercontent.com/18636280/187796006-b4436a30-8a4c-4b09-aaba-18491192da81.png)
![code-with-accordion-class](https://user-images.githubusercontent.com/18636280/187796007-c491608f-ea7a-4fb2-8978-a88239c80741.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 15.6.1

**Comment by fsbraun** [comment]
@greyhare Again well spotted! Thanks very much for pointing this out!

PR is coming up!

**Comment by fsbraun** [comment]
That sounds interesting! Do you think this page or screenshots of it would be sharable, e.g. in the docs?

**Comment by greyhare** [comment]
It'll be too big for a screenshot, but I should have a `plugins.json` I can upload.

It's been slow going, so don't hold your breath.

**Comment by fsbraun** [comment]
Solved with #53
