### ISSUE TITLE
Missing `bundle.utilities.js`

### ISSUE THREAD

**Issue by greyhare** [django-cms/djangocms-frontend#52]
**Describe the bug**
`djangocms-frontend` JS code is trying to load `{% static 'djangocms_frontend/js/bundle.utilities.js' %}`, but there is no such file in `djangocms-frontend`. There *was* such a file in `djangocms-bootstrap4` at `static/djangocms_bootstrap4/js/bundle.utilities.js`.

**To Reproduce**
1. Be editing a Django CMS page. Have the JS console open.
2. Sometimes the console says `Failed to load resource` or similar for this file.

**Expected behavior**
No errors.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version 15.6.1

**Additional context**
These templates attempt to load the missing JS module:
* `contrib/tabs/templates/djangocms_frontend/admin/tabs.html`
* `contrib/utilities/templates/djangocms_frontend/admin/spacing.html`

**Comment by fsbraun** [comment]
@greyhare Thanks for reporting this! 

It is actually not a missing file but a superfluous inclusion of a static file. The functionality of the `bundle.utilities.js` has moved to `css`.

I will create a PR to fix this.

**Comment by fsbraun** [comment]
Solved with #53 . 

A tar ball is available here: https://github.com/fsbraun/djangocms-frontend/archive/refs/heads/fix/accordion.zip
