### ISSUE TITLE
Clarify `[djangocms-icon]` in README.

### ISSUE THREAD

**Issue by greyhare** [django-cms/djangocms-frontend#57]
**Describe the bug**
Output from pip:
```
Collecting djangocms-frontend[djangocms-icon]
  Downloading djangocms_frontend-0.9.3-py3-none-any.whl (337 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 337.3/337.3 kB 5.5 MB/s eta 0:00:00
WARNING: djangocms-frontend 0.9.3 does not provide the extra 'djangocms-icon'
  Downloading djangocms_frontend-0.9.1-py3-none-any.whl (321 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 321.1/321.1 kB 4.9 MB/s eta 0:00:00
WARNING: djangocms-frontend 0.9.1 does not provide the extra 'djangocms-icon'
  Downloading djangocms_frontend-0.9.0-py3-none-any.whl (296 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 5.6 MB/s eta 0:00:00
WARNING: djangocms-frontend 0.9.0 does not provide the extra 'djangocms-icon'
  Downloading djangocms_frontend-0.2.0-py3-none-any.whl (260 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 260.6/260.6 kB 5.1 MB/s eta 0:00:00
WARNING: djangocms-frontend 0.2.0 does not provide the extra 'djangocms-icon'
```

Is the README out of date?

**To Reproduce**
Put this in your `requirements.txt`:
```
djangocms-frontend[djangocms-icon]
```

**Expected behavior**
Installation without complaint.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Python: 3.10.6

**Comment by fsbraun** [comment]
I believe the optional `djangocms-frontend[djangocms-icon]` was added in 0.9.4. Not sure why pip did not try `djangocms_frontend-0.9.4-py3-none-any.whl`. If you pinned to a version below 0.9.4, pls. remove the `[djangocms-icon]` part. It will be installed automatically.

**Comment by marksweb** [comment]
@greyhare that extra option came in with #36 towards the end of May.

All those versions you've listed are older than that so it's correct. The option doesn't exist.

**Comment by greyhare** [comment]
I had no pin. I'll try pinning 0.9.4 and see what it complains about.

**Comment by greyhare** [comment]
When I don't pin the version, it installs `django-entangled-0.5.3 djangocms-cascade-2.3.12 djangocms-frontend-0.2.0`

When I pin the version to 0.9.4, it installs `django-entangled-0.4 djangocms-cascade-2.1.7 djangocms-frontend-0.9.4`

I have `django-entangled` and `djangocms-cascade` in my `requirements.txt` with no extras or pins set.

**Comment by fsbraun** [comment]
OK, there seems to be a competing dependency of both frontend and cascade on django-entangled. For the time being, I suggest to pin to >= 0.9.4. From v1 on the dependency of frontend on django-entangled will be loosened to allow versions >0.4.

**Comment by fsbraun** [comment]
@grehare Is this resolved? If so, would you close the issue? 
(Frankly, I realized that the pinning to `django-entangled` has not been loosened in v1 yet. Later versions do not support Django 3.2. I will also check if there is an alternative to avoid this competing dependency.)

**Comment by greyhare** [comment]
I'm really getting tired of Django packages not supporting the LTS versions. 3.2 is supported for another year and a half.

There was some other thing a couple years back that decided they needed a nifty feature in Django 3.1, bumped their major version number, and exploded the Django-Shop cookie cutter template I was trying to use, as well as several other things that didn't have a version constraint in their requirements.

Anyway, I consider the version requirement a workaround, TBH. I didn't realize you weren't working this bug further and I was supposed to close the ticket.

**Comment by fsbraun** [comment]
**djangocms-frontend 1.0.1 drops pinning `django-entangled`** (and so can you). The issue should now be fully resolved.
