### ISSUE TITLE
Small cosmetic issue with Header plugin (extra space before close)

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [django-cms/djangocms-frontend#65]
**Describe the bug**

**To Reproduce**
1. Add Heading plugin
2. Publish
3. Check page source
4. See issue

**Expected behavior**
Tag closing have to be without extra space

**Screenshots**
![ksnip_20220922-140801](https://user-images.githubusercontent.com/22169129/191743190-dd554a3d-ee70-4e1c-9f49-94e127b94d99.png)

**Desktop (please complete the following information):**
not related to issue

**Additional context**

**Comment by fsbraun** [comment]
Hello @jpVm5jYYRE1VIKL ! (Not sure how to pronounce that, sorry!) Thanks for pointing that out.

**Comment by fsbraun** [comment]
Can you show which versions you are using? I cannot reproduce the effect? Also, is there an attribute set in "Advanced settings"?

**Comment by jpVm5jYYRE1VIKL** [comment]
Issue visible if to use option View Page Source in browsers. Also visible if to use "curl" . And not visible if to use developer tools i presume because developer tools execute preparsing

**Comment by fsbraun** [comment]
You're right, of course! Turned out to be a nasty little bug. Will create a pr and be resolved. :-) Thanks, once more!
