### ISSUE TITLE
Wrong setting name `DJANGOCMS_PICTURE_RESPONSIVE_IMAGES`

### ISSUE THREAD

**Issue by adrien-delhorme** [django-cms/djangocms-frontend#93]
https://github.com/django-cms/djangocms-frontend/blob/9f7853379e74816950845de569c4fcae52f5e98b/djangocms_frontend/contrib/image/models.py#L80

This is a setting of djangocms-picture package.

It is not referenced in the documentation.

**Comment by fsbraun** [comment]
Hi @adrien-delhorme, thanks for pointing that out. It is supposed to use the djangocms_picture setting to avoid duplicating settings. But it should be mentioned in the docs....

**Comment by fsbraun** [comment]
Updated the docs: https://djangocms-frontend.readthedocs.io/en/latest/reference.html#settings
