### ISSUE TITLE
Can not extend LinkPlugin as documented

### ISSUE THREAD

**Issue by bielfrontera** [django-cms/djangocms-frontend#95]
I've been following [the documentation](https://djangocms-frontend.readthedocs.io/en/latest/howto_guides.html#how-to-extend-existing-plugins) to extend the LinkPlugin. And I get this error when I try to add a LinkPlugin into a Page:
```django.core.exceptions.FieldError: Unknown field(s) (<name_of_new_field>) specified for Link. Check fields/fieldsets/exclude attributes of class LinkPlugin.```

I've found that [LinkForm](https://github.com/django-cms/djangocms-frontend/blob/master/djangocms_frontend/contrib/link/forms.py#L301) does not inherit from a `mixin_factory` as other plugins do. Is this intentional or there will be no problem to include this inheritance at LinkForm?

**Comment by fsbraun** [comment]
Just by glimpsing at it, I believe the mixin_factory is missing. It should add the field to the form. Can you add a mixin_factory and test it?

**Comment by bielfrontera** [comment]
Yes, adding the mixin_factory solves the problem. I've run the tests, are they are ok (but I've found no test for theme extension and its not trivial to add one).

I'm preparing a PR with the change.
