### ISSUE TITLE
Carousel invalid "pause" option values

### ISSUE THREAD

**Issue by adrien-delhorme** [django-cms/djangocms-frontend#99]
According to [Bootstrap documentation](https://getbootstrap.com/docs/5.3/components/carousel/#options
), it seems that `mouseleave` and `mouseenter` are not valid values for the carousel "pause" option:
https://github.com/django-cms/djangocms-frontend/blob/05491166c37296f5f95ec6e4dd2730b3a037febb/djangocms_frontend/contrib/carousel/constants.py#L6-L7

**Comment by fsbraun** [comment]
Well spotted! Thank you. A fix is in the make!
